frr version 10.4.5
frr defaults traditional
hostname r2
service integrated-vtysh-config
!
interface lo
 ip address 2.2.2.2/32
!
interface eth1
 ip address 10.0.12.2/24
!
interface eth2
 ip address 10.0.23.2/24
!
router bgp 65002
 bgp router-id 2.2.2.2
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 neighbor 10.0.12.1 remote-as 65001
 neighbor 10.0.23.3 remote-as 65003
 !
 address-family ipv4 labeled-unicast
  network 2.2.2.2/32
  neighbor 10.0.12.1 activate
  neighbor 10.0.12.1 next-hop-self
  neighbor 10.0.23.3 activate
  neighbor 10.0.23.3 next-hop-self
 exit-address-family
!
line vty