frr version 10.2.1
frr defaults traditional
hostname r1
service integrated-vtysh-config
!
interface lo
 ip address 1.1.1.1/32
!
interface eth1
 ip address 10.0.12.1/30
!
router bgp 65001
 bgp router-id 1.1.1.1
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 neighbor 10.0.12.2 remote-as 65002
 !
 address-family ipv4 labeled-unicast
  network 1.1.1.1/32
  neighbor 10.0.12.2 activate
 exit-address-family
!
line vty